# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  jLeft_1:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  jLeft_2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  jLeft_3:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  jLeft_4:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  jLeft_5:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  jLeft_6:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  jLeft_7:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  jRight_1:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  jRight_2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  jRight_3:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  jRight_4:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  jRight_5:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  jRight_6:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  jRight_7:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  leftpanda_joint1:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  leftpanda_joint2:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  leftpanda_joint3:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  leftpanda_joint4:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  leftpanda_joint5:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: false
    max_acceleration: 0
  leftpanda_joint6:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: false
    max_acceleration: 0
  leftpanda_joint7:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: false
    max_acceleration: 0
  rightpanda_joint1:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  rightpanda_joint2:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  rightpanda_joint3:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  rightpanda_joint4:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: false
    max_acceleration: 0
  rightpanda_joint5:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: false
    max_acceleration: 0
  rightpanda_joint6:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: false
    max_acceleration: 0
  rightpanda_joint7:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: false
    max_acceleration: 0